web/router.ex
defmodule Artus.Router do
  use Artus.Web, :router
  # use Plug.ErrorHandler

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NavigationHistory.Tracker
  end

  pipeline :auth do
    plug Artus.Auth.Pipeline
    plug :put_current_user
    plug :put_socket_token
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :ensure_admin do
    plug :check_admin
  end

  # Uses EmailPreviewPlug in development environment
  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  scope "/", Artus do
    pipe_through [:browser, :auth]

    # General routes
    get "/", PageController, :index
    get "/nojs", PageController, :nojs
    get "/noie", PageController, :noie
    get "/about", PageController, :about
    get "/imprint", PageController, :imprint
    get "/feedback", PageController, :feedback
    post "/feedback", PageController, :submit_feedback
    get "/tutorial", PageController, :tutorial

    # Query
    get "/advanced", QueryController, :advanced
    get "/search", QueryController, :search
    post "/advanced-search", QueryController, :advanced_search
    get "/query/:id", QueryController, :query
    post "/query/:id", QueryController, :query_sort

    # Authentication
    get "/login", AuthController, :login
    post "/auth", AuthController, :auth
    get "/logout", AuthController, :logout
    get "/activate/:code", AuthController, :activate
    get "/forgot", AuthController, :forgot
    post "/send_reset", AuthController, :send_reset
    post "/set_pass/:code", AuthController, :set_pass
    post "/reset_pass/:code", AuthController, :reset_pass
    get "/reset/:code", AuthController, :reset

    # Entries
    get "/entries/:id", EntryController, :show
    get "/entries/:id/export", EntryController, :export
    get "/entries/:id/export/:type", EntryController, :export_type
  end

  # Routes for users
  scope "/", Artus do
    pipe_through [:browser, :auth, :ensure_auth]

    # Account
    get "/account", PageController, :account

    # Entries, user routes
    get "/entries/:id/review", EntryController, :review
    get "/entries/:id/reprint", EntryController, :reprint
    get "/entries/:id/article", EntryController, :article
    
    # Entries, owner routes
    get "/entries/:id/edit", EntryController, :edit
    get "/entries/:id/delete", EntryController, :delete
    get "/entries/:id/move/:target", EntryController, :move

    # Input form
    get "/input/:cache", InputController, :input
    get "/input", InputController, :input

    # Working caches
    resources "/caches", CacheController, except: [:delete]
    get "/caches/:id/delete", CacheController, :delete
    get "/caches/:id/up", CacheController, :up
    get "/caches/:id/down", CacheController, :down
    get "/caches/:id/publish", CacheController, :publish
    post "/caches/:id/send/:direction", CacheController, :send
  end

  # Admin routes
  scope "/admin", Artus.Admin do
    pipe_through [:browser, :auth, :ensure_auth, :ensure_admin]

    get "/", PageController, :index
    get "/stats", PageController, :stats
    get "/logs", PageController, :logs
    get "/notice", PageController, :notice
    post "/set_notice", PageController, :set_notice
    get "/backup", PageController, :backup

    # Tags
    get "/tags", TagController, :index

    # Users
    resources "/users", UserController, except: [:delete]
    get "/users/:id/delete", UserController, :delete
    get "/users/:id/reset", UserController, :reset
    get "/users/:id/caches", UserController, :caches

    # Abbreviations
    resources "/abbreviations", AbbreviationController, except: [:delete]
    get "/abbreviations/:id/delete", AbbreviationController, :delete
  end

  @doc "Assigns current user to connection"
  defp put_current_user(conn, _) do
    conn
    |> assign(:user, Guardian.Plug.current_resource(conn))
  end

  @doc "Assigns websocket token to connection"
  defp put_socket_token(conn, _) do
    if current_user = conn.assigns.user do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  @doc "Checks, if assigned user has admin rights"
  defp check_admin(conn, _) do
    if conn.assigns.user.admin do
      conn
    else
      conn
      |> put_flash(:info, "You have no admin rights!")
      |> redirect(to: "/")
    end
  end

end

web/models/query.ex
defmodule Artus.Query do
  @moduledoc "Model for BIAS queries"
  use Artus.Web, :model

  schema "queries" do
    field :uuid, :string
    field :request, :string
    field :created_at, :naive_datetime
    field :views, :integer

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:uuid, :request, :created_at, :views])
    |> validate_required([:uuid, :request, :created_at, :views])
  end
end

web/controllers/query_controller.ex
defmodule Artus.QueryController do
  use Artus.Web, :controller
  import Ecto.Query

  # TODO: Refactor this mess
  
  def search(conn, %{"q" => query} = params) do
    opts = case is_nil(conn.assigns.user) do
      true -> %{
          "filters" => [
            %{"type" => "all", "params" => %{"string" => query}},
            %{"type" => "public", "params" => %{"public" => is_nil(conn.assigns.user)}}
          ]}
      false -> %{
          "filters" => [%{"type" => "all", "params" => %{"string" => query}}]
      }
    end
    
    id = Artus.QueryRunner.create(opts)
    {:ok, query_time, results} = Artus.QueryRunner.run(id, params)
    
    render conn, "search.html", %{query: query, query_time: query_time, results: results.entries, page: results}
  end
  
  def advanced(conn, _params) do
    render conn, "advanced.html"
  end

  def query(conn, %{"id"=>id}) do
    case Artus.QueryRunner.run(id) do
      {:err, :notfound} ->
        render conn, "vanished.html"
      {:ok, query_time, results} ->
        render conn, "query.html", %{sort: nil, query_id: id, query_time: query_time, results: results}
    end
  end

  def query_sort(conn, %{"id" => id, "sort" => sort}) do
    case Artus.QueryRunner.run_sorted(id, sort) do
      {:err, :notfound} ->
        render conn, "vanished.html"
      {:ok, query_time, results} ->
        render conn, "query.html", %{sort: sort, query_id: id, query_time: query_time, results: results}
    end
  end
end

web/views/query_view.ex
defmodule Artus.QueryView do
  use Artus.Web, :view
  import Scrivener.HTML

  @doc "Returns query information string depending on results"
  def query_info(result_count, query_time) do
    case result_count do
      0 -> "No matching entry was found."
      1 -> "1 result, #{query_time} ms"
      count -> "#{count} results, #{query_time} ms"
    end
  end
end

web/templates/query/advanced.html.eex
<%= render Artus.SharedView, "navbar.html", user: @user %>

<div class="container main">
  <%= render Artus.SharedView, "alert.html", %{conn: @conn} %>
  <script>window.userToken = "<%= assigns[:user_token] %>";</script>
  <script>window.systemType = 42;</script>
  <div id="reactAdvancedSearch"></div>
</div>

<div id="builder-basic"></div>

web/templates/query/index.html.eex
<%= render Artus.SharedView, "navbar.html", user: @user %>

<div class="container main">
  <%= render Artus.SharedView, "alert.html", %{conn: @conn} %>

  <%= form_tag("/search") %>
  <fieldset>
    <div class="input-group">
      <input name="query" type="text" class="form-control" placeholder="Search BIAS" value="<%= @query_str %>">
      <span class="input-group-btn">
        <button class="btn btn-secondary" type="submit">Go!</button>
      </span>
    </div>
    <a class="float-right" href="<%= query_path(@conn, :advanced) %>"><small>Advanced search</small></a>
  </fieldset>
  </form>

  <div class="alert alert-info query-time">
    <%= length(@results) %> results, <%= @query_time %>ms
  </div>
  
  <div class="list-group">
    <%= for item <- @results do %>
      <div class="list-group-item"> 
        <a href="<%= entry_path(@conn, :show, item.id) %>">
          <%= render Artus.SharedView, "entry.html", %{entry: item} %>
        </a>

        <%= if item.reviews != [] do %>
          <a style="z-index: 0;" class="float-right" data-toggle="collapse" href="#reviews<%= item.id %>" aria-expanded="false" aria-controls="collapseExample">
            <i class="fa fa-fw fa-plus-circle" aria-hidden="true"></i>
          </a>
          <div class="collapse" id="reviews<%= item.id %>">
            <br>
            <%= render Artus.SharedView, "reviews.html", %{entry_id: item.id, conn: @conn, reviews: item.reviews} %>
          </div>
        <% end %>

      </div>
    <% end %>
  </div>
</div>

web/templates/query/query.html.eex
<%= render Artus.SharedView, "navbar.html", assigns %>

<div class="container main">
  <%= render Artus.SharedView, "alert.html", assigns %>

  <div class="mb-2 card">
    <div class="card-body p-3">
      
      <%= form_tag(query_path(@conn, :query_sort, @query_id), class: "form-group row", style: "margin-bottom: 0;") %>

      <span class="col-sm-12 col-md-8 col-form-label">
        <%= query_info(length(@results), @query_time) %>
      </span>

      <%= if length(@results) > 0 do %>
        <label class="col-sm-3 col-md-1 col-form-label"><span class="float-right">Sort by</span></label>
        <div class="col-sm-3 col-md-3">
          <select id="sortSelect" name="sort" onchange="this.form.submit();" class="form-control float-right" style="border-radius: 0px;">
            <option value="titl_title">Title</option>
            <option value="author">Author</option>
            <option value="editor">Editor</option>
            <option value="ser_year_pub">Year</option>
          </select>
        </div>

        <script>
          if ("<%= @sort %>".length != 0) {
            document.getElementById("sortSelect").value = "<%= @sort %>";
          } else {
            document.getElementById("sortSelect").value = "titl_title";
          }

        </script>
      <% end %>
    </form>

    </div>
</div>

<div class="list-group">
  <%= for item <- @results do %>
    <div class="list-group-item"> 
      <a href="<%= entry_path(@conn, :show, item.id) %>">
        <%= render Artus.SharedView, "entry.html", %{entry: item} %>
      </a>

      <%= if item.reviews != [] do %>
        <a style="z-index: 0;" class="float-right" data-toggle="collapse" href="#reviews<%= item.id %>" aria-expanded="false" aria-controls="collapseExample">
          <i class="fa fa-fw fa-plus-circle" aria-hidden="true"></i>
        </a>
        <div class="collapse" id="reviews<%= item.id %>">
          <br>
          <%= render Artus.SharedView, "reviews.html", %{conn: @conn, entry: item} %>
        </div>
      <% end %>

    </div>
  <% end %>
</div>
</div>

web/templates/query/search.html.eex
<%= render Artus.SharedView, "navbar.html", assigns %>

<div class="container main">
  <%= render Artus.SharedView, "alert.html", assigns %>

  <!-- Search bar -->
  <div id="reactSearchBar"></div>

  <small class="text-muted">
    <%= query_info(@page.total_entries, @query_time) %>
  </small>

  <div class="list-group" style="margin-top: 33px;">
    <%= for item <- @results do %>
      <div class="list-group-item"> 
        <a href="<%= entry_path(@conn, :show, item.id) %>">
          <%= render Artus.SharedView, "entry.html", %{entry: item} %>
        </a>

        <%= if item.reviews != [] do %>
          <a style="z-index: 0;" class="float-right" data-toggle="collapse" href="#reviews<%= item.id %>" aria-expanded="false" aria-controls="collapseExample">
            <i class="fa fa-fw fa-plus-circle" aria-hidden="true"></i>
          </a>
          <div class="collapse" id="reviews<%= item.id %>">
            <br>
            <%= render Artus.SharedView, "reviews.html", %{conn: @conn, entry: item} %>
          </div>
        <% end %>

      </div>
    <% end %>
  </div>

  <br>
  <%= pagination_links @page, q: @query, previous: ~E(<i class="fa fa-chevron-left"></i>), next: ~E(<i class="fa fa-chevron-right"></i>) %>
</div>

web/templates/query/vanished.html.eex
<%= render Artus.SharedView, "navbar.html", user: @user %>

<div class="container main">
  <%= render Artus.SharedView, "alert.html", %{conn: @conn} %>

  <div class="alert alert-warning query-time">
    <p>The query you're looking for does not exist anymore.</p>
  </div>
  
</div>