web/router.ex
defmodule Artus.Router do
  use Artus.Web, :router
  # use Plug.ErrorHandler

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NavigationHistory.Tracker
  end

  pipeline :auth do
    plug Artus.Auth.Pipeline
    plug :put_current_user
    plug :put_socket_token
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :ensure_admin do
    plug :check_admin
  end

  # Uses EmailPreviewPlug in development environment
  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  scope "/", Artus do
    pipe_through [:browser, :auth]

    # General routes
    get "/", PageController, :index
    get "/nojs", PageController, :nojs
    get "/noie", PageController, :noie
    get "/about", PageController, :about
    get "/imprint", PageController, :imprint
    get "/feedback", PageController, :feedback
    post "/feedback", PageController, :submit_feedback
    get "/tutorial", PageController, :tutorial

    # Query
    get "/advanced", QueryController, :advanced
    get "/search", QueryController, :search
    post "/advanced-search", QueryController, :advanced_search
    get "/query/:id", QueryController, :query
    post "/query/:id", QueryController, :query_sort

    # Authentication
    get "/login", AuthController, :login
    post "/auth", AuthController, :auth
    get "/logout", AuthController, :logout
    get "/activate/:code", AuthController, :activate
    get "/forgot", AuthController, :forgot
    post "/send_reset", AuthController, :send_reset
    post "/set_pass/:code", AuthController, :set_pass
    post "/reset_pass/:code", AuthController, :reset_pass
    get "/reset/:code", AuthController, :reset

    # Entries
    get "/entries/:id", EntryController, :show
    get "/entries/:id/export", EntryController, :export
    get "/entries/:id/export/:type", EntryController, :export_type
  end

  # Routes for users
  scope "/", Artus do
    pipe_through [:browser, :auth, :ensure_auth]

    # Account
    get "/account", PageController, :account

    # Entries, user routes
    get "/entries/:id/review", EntryController, :review
    get "/entries/:id/reprint", EntryController, :reprint
    get "/entries/:id/article", EntryController, :article
    
    # Entries, owner routes
    get "/entries/:id/edit", EntryController, :edit
    get "/entries/:id/delete", EntryController, :delete
    get "/entries/:id/move/:target", EntryController, :move

    # Input form
    get "/input/:cache", InputController, :input
    get "/input", InputController, :input

    # Working caches
    resources "/caches", CacheController, except: [:delete]
    get "/caches/:id/delete", CacheController, :delete
    get "/caches/:id/up", CacheController, :up
    get "/caches/:id/down", CacheController, :down
    get "/caches/:id/publish", CacheController, :publish
    post "/caches/:id/send/:direction", CacheController, :send
  end

  # Admin routes
  scope "/admin", Artus.Admin do
    pipe_through [:browser, :auth, :ensure_auth, :ensure_admin]

    get "/", PageController, :index
    get "/stats", PageController, :stats
    get "/logs", PageController, :logs
    get "/notice", PageController, :notice
    post "/set_notice", PageController, :set_notice
    get "/backup", PageController, :backup

    # Tags
    get "/tags", TagController, :index

    # Users
    resources "/users", UserController, except: [:delete]
    get "/users/:id/delete", UserController, :delete
    get "/users/:id/reset", UserController, :reset
    get "/users/:id/caches", UserController, :caches

    # Abbreviations
    resources "/abbreviations", AbbreviationController, except: [:delete]
    get "/abbreviations/:id/delete", AbbreviationController, :delete
  end

  @doc "Assigns current user to connection"
  defp put_current_user(conn, _) do
    conn
    |> assign(:user, Guardian.Plug.current_resource(conn))
  end

  @doc "Assigns websocket token to connection"
  defp put_socket_token(conn, _) do
    if current_user = conn.assigns.user do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  @doc "Checks, if assigned user has admin rights"
  defp check_admin(conn, _) do
    if conn.assigns.user.admin do
      conn
    else
      conn
      |> put_flash(:info, "You have no admin rights!")
      |> redirect(to: "/")
    end
  end

end

web/models/entry.ex
defmodule Artus.Entry do
  @moduledoc "Model for bibliographic entries"
  use Artus.Web, :model

  schema "entries" do
    # Type and part
    field :type, :string
    field :part, :integer

    # Metadata
    field :submit_date, :naive_datetime
    field :public, :boolean

    # Form fields
    field :biblio_record_id, :string
    field :author, :string
    field :editor, :string
    field :editor_primary_work, :string
    field :reviewer, :string
    field :titl_title, :string
    field :titl_subtitle, :string
    field :titl_add, :string
    field :ser_title, :string
    field :ser_volume, :integer
    field :ser_code, :string
    field :ser_issue, :integer
    field :ser_count, :string
    field :ser_year_pub, :integer
    field :publ_pub_house, :string
    field :publ_pub_place, :string
    field :biblio_issn, :string
    field :biblio_isbn, :string
    field :doi, :string
    field :language, :string
    
    # Textbox form entries (text type!)
    field :abstract, :string
    field :internal_comment, :string
    field :additional_info, :string 
    field :links, :string

    # Tags
    many_to_many :tags, Artus.Tag, join_through: "entries_tags", on_delete: :delete_all

    # Associated entries (reviews, reprints, children)
    has_many :reviews, Artus.Entry, foreign_key: :review_parent_id, on_delete: :delete_all
    has_many :reprints, Artus.Entry, foreign_key: :reprint_parent_id, on_delete: :delete_all
    has_many :children, Artus.Entry, foreign_key: :children_parent_id, on_delete: :delete_all

    belongs_to :review_parent, Artus.Entry, foreign_key: :review_parent_id, on_replace: :nilify
    belongs_to :reprint_parent, Artus.Entry, foreign_key: :reprint_parent_id, on_replace: :nilify
    belongs_to :children_parent, Artus.Entry, foreign_key: :children_parent_id, on_replace: :nilify

    # Ownerships (cache, user) 
    belongs_to :cache, Artus.Cache, on_replace: :nilify
    belongs_to :user, Artus.User, on_replace: :nilify
    
    field :bibliographer, :string
    field :last_change_user, :string

    timestamps()
  end

  defp normalize_model(model) do
    model
    |> Enum.map(fn({k, v}) -> 
      if is_map(v) do
        case k do
          "ser_code" -> {k, v["abbr"]}
          _ -> {k, v["value"]}
        end
    else
      {k, v}
      end
    end)
    |> Enum.into(%{})
  end

  def submit_changeset(model, user, cache, params \\ %{}) do
    fields = Artus.DefinitionManager.fields()
    params = params
             |> normalize_model()

    type = params["type"]
    type_fields = fields[type] |> Enum.reject(&Enum.member?(~w(subject_things subject_works), hd(&1))) 
    permitted = type_fields |> Enum.map(&hd(&1))
    permitted = permitted ++ ["type", "part"]
    required = type_fields 
               |> Enum.filter(fn(x) -> Enum.at(x, 1) == true end) 
               |> Enum.map(&hd(&1))
               |> Enum.map(&String.to_atom(&1))
               
    model
    |> cast(params, permitted)
    |> validate_required(required)
    |> put_change(:public, false)
    |> put_change(:last_change_user, user.name)
    |> put_assoc(:cache, cache, required: true)
    |> put_assoc(:user, user, required: true)
  end

  def changeset(model, params \\ %{}) do
    model
    |> cast(params, ~w(bibliographer biblio_record_id type part public author editor editor_primary_work reviewer
                       titl_title titl_subtitle titl_add ser_title ser_volume ser_code ser_year_pub 
                       publ_pub_house publ_pub_place biblio_issn biblio_isbn doi abstract language
                       ser_issue ser_count additional_info links internal_comment))
    |> cast_assoc(:cache, required: false)
    |> cast_assoc(:user, required: true)
  end
  
  def publish_changeset(model) do
    # ~w(type part submit_date public biblio_record_id author editor editor_primary_work reviewer titl_title titl_subtitle titl_add ser_title ser_volume ser_code ser_issue ser_count ser_year_pub publ_pub_house publ_pub_place biblio_issn biblio_isbn doi language abstract internal_comment additional_info links bibliographer last_change_user))
    model
    |> cast(%{}, [])
    |> put_change(:public, true)
    |> put_assoc(:cache, nil)
  end
end

web/controllers/entry_controller.ex
defmodule Artus.EntryController do
  @moduledoc "Controller for all bibliographic entry pages"

  use Artus.Web, :controller
  alias Artus.{Entry, Cache, EventLogger}

  plug :fetch_entry
  plug :check_public when action in [:show, :export, :export_type]
  plug :check_ownership when action in [:move, :edit, :delete]

  @doc "Shows entry by ID"
  def show(conn, %{"id" => id}) do
    owner = is_owner?(conn.assigns.entry, conn.assigns.user)
    render(conn, "show.html", %{entry: conn.assigns.entry, is_owner: owner})
  end

  @doc "Renders review input form for entry"
  def review(conn, %{"id" => id}) do
    render(conn, "review.html", %{entry: conn.assigns.entry})
  end

  @doc "Renders reprint input form for entry"
  def reprint(conn, %{"id" => id}) do
    render(conn, "reprint.html", %{entry: conn.assigns.entry})
  end

  @doc "Renders article input form for entry"
  def article(conn, %{"id" => id}) do
    render(conn, "article.html", %{entry: conn.assigns.entry})
  end

  @doc "Renders edit form"
  def edit(conn, %{"id" => id}) do
    render(conn, "edit.html", %{entry: conn.assigns.entry})
  end

  @doc "Deletes entry"
  def delete(conn, %{"id" => id}) do
    Repo.delete!(conn.assigns.entry)
    EventLogger.log(:entry_delete, "#{conn.assigns.user.name} deleted entry ##{conn.assigns.entry.id}")

    conn 
    |> put_flash(:info, "Entry deleted successfully.")
    |> redirect(to: NavigationHistory.last_path(conn, 2))
  end

  @doc "Moves entry to target working cache"
  def move(conn, %{"id" => id, "target" => target}) do
    target_cache = Repo.get!(Cache, target)

    conn.assigns.entry
    |> Ecto.Changeset.change
    |> Ecto.Changeset.put_assoc(:cache, target_cache)
    |> Repo.update!()

    EventLogger.log(:entry_move, "#{conn.assigns.user.name} moved entry ##{id} to working cache '#{target_cache.name}' (#{target_cache.id})")

    conn
    |> put_flash(:info, "Successfully moved entry to working cache '#{target_cache.name}'.")
    |> redirect(to: entry_path(conn, :show, id))
  end

  @doc "Renders export page"
  def export(conn, %{"id" => id}) do
    render(conn, "export.html", %{entry: conn.assigns.entry})
  end

  @doc "Exports entry as file"
  def export_type(conn, %{"id" => id, "type" => type}) do
    # Renders entry snippet as HTML
    entry = conn.assigns.entry
    entry_html = Phoenix.View.render_to_string(Artus.SharedView, "entry.html", %{entry: entry})
    base_name = "bias_export_#{entry.id}"

    # Writes rendered entry to temporary file
    file_path = Temp.path!(base_name <> ".html")
    fd = File.open!(file_path, [:write, :utf8])
    IO.write(fd, entry_html)
    File.close(fd)

    filetypes = ~w(rtf latex odt)
    case Enum.member?(filetypes, type) do
      true ->
        out_filename = base_name <> "." <> type
        ofile_path = Temp.path!(out_filename)
        convert_file(file_path, ofile_path, type, id)

        conn
        |> put_resp_header("content-disposition", ~s(attachment; filename="#{out_filename}"))
                                                                          |> send_file(200, ofile_path)
      false ->
        conn
        |> put_flash(:info, "Not an accepted export filetype!")
        |> redirect(to: entry_path(conn, :show, id))
    end
  end

  @doc "Converts html input file to output file of specified type, using pandoc"
  defp convert_file(input, output, type, id) do
    System.cmd("pandoc", [input, "-f", "html", "-t", type, "-s", "-o", output])
  end

  @doc "Checks if user owns entry or is admin"
  defp is_owner?(entry, user) do
    case user do
      nil -> false
      user -> (!entry.public && (entry.user.id == user.id)) || user.admin
    end
  end

  @doc "Fetches entry and assigns it to connection"
  defp fetch_entry(conn, _) do
    preloads = [{:user, :caches}, :tags, :cache, :reviews, :reprints, :children]
    entry = Entry |> Repo.get!(conn.params["id"]) |> Repo.preload(preloads)
    assign(conn, :entry, entry)
  end

  @doc "Checks if entry is public or accessed by user"
  defp check_public(conn, _) do
    if !is_nil(conn.assigns.user) || conn.assigns.entry.public do
      conn
    else
      conn 
      |> put_flash(:info, "You do not have access to this entry.") 
      |> redirect(to: "/")
      |> halt()
    end
  end

  @doc "Checks ownership (or, alternatively, admin-hood) of entry"
  def check_ownership(conn, _) do
    user = conn.assigns.user

    if is_owner?(conn.assigns.entry, user) do
      conn
    else
      conn
      |> put_flash(:info, "You do not have sufficient rights to perfom this action.")
      |> redirect(to: NavigationHistory.last_path(conn, 1))
      |> halt()
    end
  end
end

web/views/entry_view.ex
defmodule Artus.EntryView do
  use Artus.Web, :view

  import Ecto.Query
  alias Artus.Repo
  alias Artus.Tag
  alias Artus.Cache

  # TODO: Branch in Entry? Part/Type in Entry?

  def render_tag(tag) do
    tag.tag |> Artus.NotMarkdown.to_html()
  end

  def get_label(key) do
    field_defs = Artus.DefinitionManager.field_defs
    case field_defs[key] do
      nil -> inspect key
      "type" -> "Type"
      x -> x["label"]
    end
  end

  def get_language(language) do
    lang_defs = Artus.DefinitionManager.languages
    l_filtered = lang_defs |> Enum.filter(fn(l) -> l["value"] == language end) |> hd
    l_filtered["label"]
  end

  def get_part(part_number) do
    if part_number == 3 do
      "Reprint"
    else
      option_defs = Artus.DefinitionManager.options
      o_filtered = option_defs["parts"] 
                   |> Enum.filter(fn(o) -> o["value"] == part_number end) |> hd
      o_filtered["label"]
    end
  end
  
  def get_type(type) do
    if type == "r" do
      "Review"
    else
      option_defs = Artus.DefinitionManager.options
      o_filtered = option_defs["types"] |> Enum.filter(fn(o) -> o["value"] == type end) |> hd
      o_filtered["label"]
    end
  end

  @doc "Returns DOI referer link"
  def doi_link(doi) do
    # TODO: Check DOI with Regex
    "https://dx.doi.org/" <> doi
  end

  def get_branch(branch_int) do
    branches = Artus.DefinitionManager.branches
    case branches["#{branch_int}"] do
      x -> x
    end
  end

  def belongs_to_user?(user_id, entry_id) do
    query = from c in Cache,
            where: c.user == ^(user_id),
            select: c.entries
    query |> Repo.all |> List.flatten |> Enum.member?(entry_id)
  end
  
  @doc """
  Prepares entry for table rendering

  It fetches the keys from the `DefinitionManager` and
  builds a keyword list using the keys and the entry
  """
  def prepare_entry_table(entry) do
    entry_map = Map.from_struct(entry)
    to_remove = [:abstract, :internal_comment]
    
    Artus.DefinitionManager.fields()[entry.type]
    |> Enum.map(fn [k, _] -> String.to_atom(k) end)
    |> (&(&1 -- to_remove)).()
    |> Enum.map(fn(k) -> {k, entry_map[k]} end)
    |> Enum.filter(fn({k, v}) -> !is_nil(v) end)
  end


  def render_label(:part), do: "Part"
  def render_label(:type), do: "Type"
  def render_label(:editor), do: "Editor(s)"
  def render_label(key) do
    key |> Atom.to_string |> get_label()
  end

  def render_value(:editor, value) do
    value |> Artus.SharedView.style_editors() |> raw()
  end
  def render_value(:author, value) do
    value |> Artus.SharedView.style_authors() |> raw()
  end
  def render_value(:part, value) do
    get_part(value)
  end
  def render_value(:doi, value) do
    render Artus.EntryView, "field_doi.html", %{doi: value}
  end
  def render_value(:language, value) do
    language_map = Artus.DefinitionManager.languages()
                   |> Enum.filter(fn(m) -> m["value"] == value end)
                   |> hd()
    case language_map["label"] do
      nil -> value
      x -> x
    end
  end
  def render_value(:links, value) do
    # TODO: Refactor field_links.html
    render Artus.EntryView, "field_links.html", %{links: value}
  end
  def render_value(key, value) do
    value
  end


  def render_entry_status(entry) do
    case entry.public do
      true -> "<span class=\"badge badge-pill badge-success\">Public</span>"
      false -> "<span class=\"badge badge-pill badge-warning\">Not public</span>"
    end
  end

end

web/templates/entry/article.html.eex
<%= render Artus.SharedView, "navbar.html", assigns %>

<div class="container main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<%= entry_path(@conn, :show, @entry.id) %>">Entry #<%= @entry.id %></a></li>
    <li class="breadcrumb-item active">Add article</li>
  </ol>

  <script>window.userToken = "<%= assigns[:user_token] %>";</script>
  <script>window.entryID = <%= @entry.id %>;</script>
  <script>window.inputType = "article";</script>

  <div id="reactInput"></div>
</div>

web/templates/entry/child.html.eex
<%= render Artus.SharedView, "navbar.html", %{user: @user} %>

<div class="container main">
  <h1>Add article</h1>

  <script>window.userToken = "<%= assigns[:user_token] %>";</script>
  <script>window.systemType = 3;</script>
  <script>window.parentID = <%= @parent_id %>;</script>

  <div id="child-form"></div>
</div>

web/templates/entry/delete_modal.html.eex
<div class="modal fade" id="entryDeleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel">Delete Entry</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>You're about to delete this entry. Please confirm your action by clicking the button below.</p>
        <div class="alert alert-warning" role="alert">
          All data linked to the entry will be lost! This includes reviews, reprints and linked entries!
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <a class="btn btn-danger" href="<%= entry_path(@conn, :delete, @entry.id) %>" role="button">Delete</a>
      </div>
    </div>
  </div>
</div>

web/templates/entry/edit.html.eex
<%= render Artus.SharedView, "navbar.html", %{user: @user} %>

<div class="container main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<%= entry_path(@conn, :show, @entry.id) %>">Entry #<%= @entry.id %></a></li>
    <li class="breadcrumb-item active">Edit entry</li>
  </ol>

  <script>window.userToken = "<%= assigns[:user_token] %>";</script>
  <script>window.entryID = "<%= @entry.id %>";</script>
  <script>window.inputType = "edit";</script>

  <div id="reactInput"></div>
</div>

web/templates/entry/export.html.eex
<%= render Artus.SharedView, "navbar.html", assigns %>

<div class="container main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<%= entry_path(@conn, :show, @entry.id) %>">Entry #<%= @entry.id %></a></li>
    <li class="breadcrumb-item active">Export entry</li>
  </ol>

  <div class="list-group">
    <a href="<%= entry_path(@conn, :export_type, @entry.id, "rtf") %>" class="list-group-item list-group-item-action" download>
      <i class="fa fa-fw fa-download" aria-hidden="true"></i> Rich Text Format <span class="badge badge-primary">.rtf</span>
    </a>
    <a href="<%= entry_path(@conn, :export_type, @entry.id, "latex") %>" class="list-group-item list-group-item-action" download>
      <i class="fa fa-fw fa-download" aria-hidden="true"></i> LaTeX  <span class="badge badge-primary">.latex</span>
    </a>
    <a href="<%= entry_path(@conn, :export_type, @entry.id, "odt") %>" class="list-group-item list-group-item-action" download>
      <i class="fa fa-fw fa-download" aria-hidden="true"></i> OpenDocument Format <span class="badge badge-primary">.odt</span>
    </a>
  </div>
  
  <p class="text-muted text-center mt-2">
    <small>
      <i class="fa fa-creative-commons"></i> This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>
    </small>
  </p>
</div>

web/templates/entry/export_type.html.eex
<%= render Artus.SharedView, "navbar.html", %{user: @user} %>

<div class="container main">
  <h2>Export entry</h2>

  <div class="list-group">
    <a href="#" class="list-group-item active">
      Cras justo odio
    </a>
    <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
    <a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
    <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
    <a href="#" class="list-group-item list-group-item-action disabled">Vestibulum at eros</a>
  </div>
  
  <a href="<%= entry_path(@conn, :show, @entry.id) %>">Back to entry</a>
</div>

web/templates/entry/field_doi.html.eex
<a target="_blank" href="<%= doi_link(@doi) %>"><%= @doi %></a>

web/templates/entry/field_links.html.eex
<%= for line <- String.split(@links, "\n", trim: true) do %>
  <% link_set = String.split(line, " ") %>
  <a href="<%= hd(link_set) %>"><%= List.last(link_set) %></a>
<% end %>

web/templates/entry/index.html.eex
<%= render Artus.SharedView, "navbar.html", %{user: @user} %>

<div class="container main">
  <h2>Working caches</h2>

  <div class="list-group">
    <%= for cache <- @caches do %>
      <a class="list-group-item" href="<%= cache_path(@conn, :show, cache.id) %>">
        <%= cache.name %>
        <span class="label label-default float-right"><%= cache.entries |> List.to_tuple |> tuple_size %></span>
      </a>
    <% end %>
  </div>

  <a class="btn btn-primary float-right add-button" href="/caches/new" role="button">New working cache</a>

</div>

web/templates/entry/move.html.eex
<%= render Artus.SharedView, "navbar.html", %{user: @user} %>

<div class="container main">
  <h2>Export entry</h2>
  <p>Export feature coming soon.</p>
  <a href="<%= entry_path(@conn, :show, @entry.id) %>">Back to entry</a>
</div>

web/templates/entry/move_modal.html.eex
<div class="modal fade" id="entryMoveModal" tabindex="-1" role="dialog" aria-labelledby="moveModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Move Entry to other Cache</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="list-group">
          <%= for cache <- @entry.user.caches do %>
            <%= if cache.id != @entry.cache.id do %>
              <a class="list-group-item" href="<%= entry_path(@conn, :move, @entry.id, cache.id) %>"><%= cache.name %></a>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

web/templates/entry/reprint.html.eex
<%= render Artus.SharedView, "navbar.html", assigns %>

<div class="container main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<%= entry_path(@conn, :show, @entry.id) %>">Entry #<%= @entry.id %></a></li>
    <li class="breadcrumb-item active">Add reprint</li>
  </ol>

  <script>window.userToken = "<%= assigns[:user_token] %>";</script>
  <script>window.entryID = <%= @entry.id %>;</script>
  <script>window.inputType = "reprint";</script>

  <div id="reactInput"></div>
</div>

web/templates/entry/review.html.eex
<%= render Artus.SharedView, "navbar.html", assigns %>

<div class="container main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<%= entry_path(@conn, :show, @entry.id) %>">Entry #<%= @entry.id %></a></li>
    <li class="breadcrumb-item active">Add review</li>
  </ol>

  <script>window.userToken = "<%= assigns[:user_token] %>";</script>
  <script>window.entryID = <%= @entry.id %>;</script>
  <script>window.inputType = "review";</script>

  <div id="reactInput"></div>
</div>

web/templates/entry/table.html.eex
<table class="table table-hover">
  <thead></thead>
  <tbody>
    <%= for {key, value} <- prepare_entry_table(@entry) do %>
      <tr>
        <th><%= render_label(key) %></th>
        <td><%= render_value(key, value) %></td>
      </tr>
    <% end %>
  </tbody>
</table>