web/router.ex
defmodule Artus.Router do
  use Artus.Web, :router
  # use Plug.ErrorHandler

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NavigationHistory.Tracker
  end

  pipeline :auth do
    plug Artus.Auth.Pipeline
    plug :put_current_user
    plug :put_socket_token
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :ensure_admin do
    plug :check_admin
  end

  # Uses EmailPreviewPlug in development environment
  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  scope "/", Artus do
    pipe_through [:browser, :auth]

    # General routes
    get "/", PageController, :index
    get "/nojs", PageController, :nojs
    get "/noie", PageController, :noie
    get "/about", PageController, :about
    get "/imprint", PageController, :imprint
    get "/feedback", PageController, :feedback
    post "/feedback", PageController, :submit_feedback
    get "/tutorial", PageController, :tutorial

    # Query
    get "/advanced", QueryController, :advanced
    get "/search", QueryController, :search
    post "/advanced-search", QueryController, :advanced_search
    get "/query/:id", QueryController, :query
    post "/query/:id", QueryController, :query_sort

    # Authentication
    get "/login", AuthController, :login
    post "/auth", AuthController, :auth
    get "/logout", AuthController, :logout
    get "/activate/:code", AuthController, :activate
    get "/forgot", AuthController, :forgot
    post "/send_reset", AuthController, :send_reset
    post "/set_pass/:code", AuthController, :set_pass
    post "/reset_pass/:code", AuthController, :reset_pass
    get "/reset/:code", AuthController, :reset

    # Entries
    get "/entries/:id", EntryController, :show
    get "/entries/:id/export", EntryController, :export
    get "/entries/:id/export/:type", EntryController, :export_type
  end

  # Routes for users
  scope "/", Artus do
    pipe_through [:browser, :auth, :ensure_auth]

    # Account
    get "/account", PageController, :account

    # Entries, user routes
    get "/entries/:id/review", EntryController, :review
    get "/entries/:id/reprint", EntryController, :reprint
    get "/entries/:id/article", EntryController, :article
    
    # Entries, owner routes
    get "/entries/:id/edit", EntryController, :edit
    get "/entries/:id/delete", EntryController, :delete
    get "/entries/:id/move/:target", EntryController, :move

    # Input form
    get "/input/:cache", InputController, :input
    get "/input", InputController, :input

    # Working caches
    resources "/caches", CacheController, except: [:delete]
    get "/caches/:id/delete", CacheController, :delete
    get "/caches/:id/up", CacheController, :up
    get "/caches/:id/down", CacheController, :down
    get "/caches/:id/publish", CacheController, :publish
    post "/caches/:id/send/:direction", CacheController, :send
  end

  # Admin routes
  scope "/admin", Artus.Admin do
    pipe_through [:browser, :auth, :ensure_auth, :ensure_admin]

    get "/", PageController, :index
    get "/stats", PageController, :stats
    get "/logs", PageController, :logs
    get "/notice", PageController, :notice
    post "/set_notice", PageController, :set_notice
    get "/backup", PageController, :backup

    # Tags
    get "/tags", TagController, :index

    # Users
    resources "/users", UserController, except: [:delete]
    get "/users/:id/delete", UserController, :delete
    get "/users/:id/reset", UserController, :reset
    get "/users/:id/caches", UserController, :caches

    # Abbreviations
    resources "/abbreviations", AbbreviationController, except: [:delete]
    get "/abbreviations/:id/delete", AbbreviationController, :delete
  end

  @doc "Assigns current user to connection"
  defp put_current_user(conn, _) do
    conn
    |> assign(:user, Guardian.Plug.current_resource(conn))
  end

  @doc "Assigns websocket token to connection"
  defp put_socket_token(conn, _) do
    if current_user = conn.assigns.user do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  @doc "Checks, if assigned user has admin rights"
  defp check_admin(conn, _) do
    if conn.assigns.user.admin do
      conn
    else
      conn
      |> put_flash(:info, "You have no admin rights!")
      |> redirect(to: "/")
    end
  end

end

web/models/cache.ex
defmodule Artus.Cache do
  @moduledoc "Model for working caches"
  use Artus.Web, :model

  schema "caches" do
    field :name, :string

    belongs_to :user, Artus.User, on_replace: :nilify
    has_many :entries, Artus.Entry, on_delete: :delete_all

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name])
    |> validate_required([:name])
    |> cast_assoc(:user, required: true)
  end

  def with_entries(query) do
    from q in query, preload: [{:entries, [:reprints, :reviews, :children]}]
  end
end

web/controllers/cache_controller.ex
defmodule Artus.CacheController do
  use Artus.Web, :controller
  
  import Ecto.Query
  alias Artus.{Entry, Cache, User, Logger}

  @doc "Shows all working caches by current user"
  def index(conn, _params) do
    caches = get_caches_by_user(conn.assigns.user)
    render conn, "index.html", %{caches: caches}
  end

  @doc "Shows form to create new working cache"
  def new(conn, _params) do
    changeset = Cache.changeset(%Cache{})
    render conn, "new.html", %{changeset: changeset}
  end

  @doc "Creates new working cache"
  def create(conn, %{"cache" => cache}) do
    changeset = Ecto.build_assoc(conn.assigns.user, :caches, %{name: cache["name"]})

    case Repo.insert(changeset) do
      {:ok, new_cache} ->
        Artus.EventLogger.log(
          :cache_create,
          "#{conn.assigns.user.name} created the working cache '#{new_cache.name}' (##{new_cache.id})")

        conn
        |> put_flash(:info, "Working Cache created successfully.")
        |> redirect(to: cache_path(conn, :index))
      {:error, changeset} ->
        render conn, "new.html", changeset: changeset
    end
  end

  @doc "Shows working cache by ID with redirect alert"
  def show(conn, %{"id" => id, "success" => type}) do
    message = case type do
      "edit" -> "Successfully edited entry!"
      "create" -> "Successfully created entry!"
    end

    cache = Cache |> Cache.with_entries() |> Repo.get!(id)
    conn
    |> put_flash(:info, message)
    |> render("show.html", %{cache: cache})
  end

  @doc "Shows working cache by ID"
  def show(conn, %{"id" => id}) do
    cache = Cache |> Cache.with_entries() |> Repo.get!(id)
    render conn, "show.html", %{cache: cache}
  end

  @doc "Shows page for sending cache upward"
  def up(conn, %{"id" => id}) do
    supervisors = get_supervisors(conn.assigns.user)
    cache = Cache |> Cache.with_entries() |> Repo.get!(id)
    render conn, "up.html", %{cache: cache, supervisors: supervisors}
  end
  
  @doc "Shows page for sending cache downward"
  def down(conn, %{"id" => id}) do
    subordinates = get_subordinates(conn.assigns.user)
    cache = Cache |> Cache.with_entries() |> Repo.get!(id)
    render conn, "down.html", %{cache: cache, subordinates: subordinates}
  end

  @doc "Sends working cache to recipient"
  def send(conn, %{"id" => id, "direction" => _direction, "recipient" => recipient, "comment" => comment}) do
    cache = Cache |> Cache.with_entries() |> Repo.get!(id)
    r_user = Repo.get!(User, recipient)

    Enum.each(cache.entries, &reassign(&1, r_user))
    send_transfer_mail(conn.assigns.user, r_user, cache, comment)
    reassign(cache, r_user)

    Artus.EventLogger.log(:cache_send, "#{conn.assigns.user.name} sent the working cache '#{cache.name}' to #{r_user.name}")

    conn
    |> put_flash(:info, "Working Cache was sent successfully.")
    |> redirect(to: cache_path(conn, :index))
  end

  @doc "Publishes all entries in cache and deletes it"
  def publish(conn, %{"id" => id}) do
    cache = Cache |> Cache.with_entries() |> Repo.get!(id)

    Enum.each(cache.entries, &publish_entry(&1))
    Repo.delete(cache)

    Artus.EventLogger.log(:cache_publish, "#{conn.assigns.user.name} published the working cache '#{cache.name}' (#{cache.id})")
    Artus.FastSearchServer.rebuild()

    conn
    |> put_flash(:info, "Successfully published the Working Cache '#{cache.name}'!")
    |> redirect(to: cache_path(conn, :index))
  end

  @doc "Delete working cache including all its entries"
  def delete(conn, %{"id" => id}) do
    cache = Repo.get!(Cache, id)
    Repo.delete!(cache)

    Artus.EventLogger.log(:cache_delete, "#{conn.assigns.user.name} delete the working cache '#{cache.name}' (#{cache.id})")

    conn
    |> put_flash(:info, "Cache deleted successfully.")
    |> redirect(to: cache_path(conn, :index))
  end


  @doc "Fetches all the working caches of a specific user"
  defp get_caches_by_user(user) do
    user
    |> Ecto.assoc(:caches)
    |> Repo.all()
    |> Enum.map(fn(cache) -> Repo.preload(cache, [:entries]) end)
  end

  @doc "Sends cache transfer mail"
  defp send_transfer_mail(from_user, user, cache, comment) do
    from_user
    |> Artus.Email.transfer_cache_email(user, cache, comment)
    |> Artus.Mailer.deliver_now
  end

  @doc "Fetches supervisors of user"
  defp get_supervisors(user) do
    query = case user.level do
      x when x == 2 ->
        from u in User, where: u.level == 1
      x when x != 2 ->
        from u in User,
        where: u.branch == ^user.branch and u.level == ^(user.level - 1)
    end
    Repo.all(query)
  end

  @doc "Fetches subordinates of user"
  defp get_subordinates(user) do
    query = case user.level do
      x when x == 1 -> 
        from u in User, where: u.level == 2
      x when x != 1 ->
        from u in User,
        where: u.branch == ^user.branch and u.level == ^(user.level + 1)
    end
    Repo.all(query)
  end

  @doc "Makes entry public and removes it from cache"
  defp publish_entry(entry) do
    p_entry = Repo.preload(entry, [:cache, :user])
    changeset = Entry.publish_changeset(p_entry)
    Repo.update!(changeset)
  end

  @doc "Reassigns entry/cache to new user"
  defp reassign(object, recipient) do
    object
    |> Repo.preload(:user)
    |> Ecto.Changeset.change
    |> Ecto.Changeset.put_assoc(:user, recipient)
    |> Repo.update!()
  end
end

web/views/cache_view.ex
defmodule Artus.CacheView do
  use Artus.Web, :view

  def inject_danger(form, field) do
    if form.errors[field] do
      "has-danger"
    end
  end

  def lookup_role(level) do
    case level do
      1 -> "International bibliographer"
      2 -> "National bibliographer"
      3 -> "Bibliographer"
    end
  end

end

web/templates/cache/delete_modal.html.eex
<div class="modal fade" id="cacheDeleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Cache</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>You're about to delete this Working Cache.<br>
          <b>The Working Cache and its entries will be irrevocably deleted!</b><br>
          Please confirm your action by clicking the button below.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <i class="fa fa-fw fa-times" aria-hidden="true"></i> Cancel
        </button>
        <a class="btn btn-danger" href="<%= cache_path(@conn, :delete, @cache.id) %>" role="button">
          <i class="fa fa-fw fa-trash" aria-hidden="true"></i> Delete
        </a>
      </div>
    </div>
  </div>
</div>

web/templates/cache/down.html.eex
<%= render Artus.SharedView, "navbar.html", %{user: @user} %>

<div class="container main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/caches">Working Caches</a></li>
    <li class="breadcrumb-item"><a href="<%= cache_path(@conn, :show, @cache.id) %>"><%= @cache.name %></a></li>
    <li class="breadcrumb-item active">Send Cache downward</li>
  </ol>

  <%= if @subordinates != [] do %>
    <div class="alert alert-info">
      You're about to send your Working Cache to a lower level of your branch. Please select a subordinate bibliographer.
    </div>

    <%= form_tag(cache_path(@conn, :send, @cache.id, :down)) %>
    <div class="form-group">
      <label for="subordinate">Subordinate / Recipient</label>
      <select class="form-control" id="recipient" name="recipient">
        <%= for subordinate <- @subordinates do %>
          <option value="<%= subordinate.id %>"><%= subordinate.name %></option>
        <% end %>
      </select>
    </div>
    
    <div class="form-group">
      <label for="comment">Comment</label>
      <textarea class="form-control" id="comment" name="comment" rows="3"></textarea>
    </div>

    <button type="submit" class="btn btn-primary float-right">
      <i class="fa fa-fw fa-arrow-down" aria-hidden="true"></i> Send down
    </button>
    </form>
  <% else %>
    <div class="alert alert-danger" role="alert">
      There is no person of your branch registered who represents a lower level.
    </div>
  <% end %>
</div>

web/templates/cache/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      Oops, something went wrong! Please check the errors below.
    </div>
  <% end %>

  <fieldset class="form-group <%= inject_danger(f, :abbr) %>">
    <%= label f, :name, "Name of the new Working Cache" %>
    <%= text_input f, :name, class: "form-control", placeholder: "" %>
    <%= error_tag f, :name %>
  </fieldset>

  <fieldset class="form-group">
    <button class="btn btn-primary float-right" type="submit">
      <i class="fa fa-fw fa-paper-plane" aria-hidden="true"></i> Create Cache
    </button>
  </fieldset>
<% end %>

web/templates/cache/help_modal.html.eex
<div class="modal fade" id="cacheHelpModal" tabindex="-1" role="dialog" aria-labelledby="helpModal" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">About Working Caches</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>A working cache is a collection of unpublished records.</p>
        <p>Every record has to be part of a working cache. Before you start entering your data, you have to create at least one working cache in order to assign the new record.</p>
        <p>The idea of the working cache is to mark a big number of records and to move them to the responsible National Bibliographer. When you start working, you may wish to enter all data in one working cache (e.g. "BIAS 68"). You may also wish to distinguish between different types (e.g. "finished", "keep in mind"). You can create and work with different working caches at the same time. The main task of the cache is to move all records to the next level. Once the bibliographers have finished their work, they are requested to submit the working cache, in order to give the National Bibliographer a sign to start work. He or she can now edit the data. During this process you are not allowed to edit the entries. When the National Bibliographer has finished work, he or she submits all working caches to the International Bibliographer who checks and edits data from all branches and then publishes them. The International Bibliographer may resend working caches back to the National Bibliographer who may then refer them to the bibliographer if necessary.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-fw fa-lightbulb-o" aria-hidden="true"></i> Ok, got it</button>
      </div>
    </div>
  </div>
</div>

web/templates/cache/index.html.eex
<%= render Artus.SharedView, "navbar.html", %{user: @user} %>

<div class="container main">
  <%= render Artus.SharedView, "alert.html", %{conn: @conn} %>
  <%= render Artus.CacheView, "help_modal.html", %{conn: @conn} %>
  
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">Working Caches</li>
  </ol>

  <%= if @caches == [] do %>
    <div class="alert alert-info">
        You have no Working Caches.
    </div>
  <% else %>
    <div class="list-group">
      <%= for cache <- @caches do %>
        <a class="list-group-item" href="<%= cache_path(@conn, :show, cache.id) %>">
          <%= cache.name %>
          <span class="label label-default float-right"><%= length(cache.entries) %></span>
        </a>
      <% end %>
    </div>
  <% end %>

  <div class="float-right">
    <button type="button" class="btn btn-secondary add-button" data-toggle="modal" data-target="#cacheHelpModal">
      <i class="fa fa-fw fa-question-circle" aria-hidden="true"></i> Help
    </button>
    <a class="btn btn-primary add-button" href="<%= cache_path(@conn, :new) %>" role="button">
      <i class="fa fa-fw fa-plus" aria-hidden="true"></i> New Working Cache
    </a>
  </div>

</div>

web/templates/cache/new.html.eex
<%= render Artus.SharedView, "navbar.html", %{user: @user} %>

<div class="container main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/caches">Working Caches</a></li>
    <li class="breadcrumb-item active">New Cache</li>
  </ol>
  
  <%= render "form.html", changeset: @changeset, action: cache_path(@conn, :create) %>
</div>

web/templates/cache/publish_modal.html.eex
<div class="modal fade" id="cachePublishModal" tabindex="-1" role="dialog" aria-labelledby="publishModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Publish Cache</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>You're about to publish this Working Cache.<br>Are you sure?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <i class="fa fa-fw fa-times" aria-hidden="true"></i> Cancel
        </button>
        <a class="btn btn-success" href="<%= cache_path(@conn, :publish, @cache.id) %>" role="button">
          <i class="fa fa-fw fa-check" aria-hidden="true"></i> Publish!
        </a>
      </div>
    </div>
  </div>
</div>

web/templates/cache/show.html.eex
<%= render Artus.SharedView, "navbar.html", %{user: @user} %>

<div class="container main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/caches">Working Caches</a></li>
    <li class="breadcrumb-item active"><%= @cache.name %></li>
  </ol>
  
  <%= render Artus.SharedView, "alert.html", assigns %>
  <%= render Artus.CacheView, "delete_modal.html", assigns %>
  <%= render Artus.CacheView, "publish_modal.html", assigns %>

  <h1 class="display-3">
    <%= @cache.name %>
  </h1>

  <div class="mb-4">
    <a class="btn btn-primary" href="<%= input_path(@conn, :input, @cache.id) %>" role="button">
      <i class="fa fa-fw fa-plus" aria-hidden="true"></i> Add entry
    </a>
    <%= if @user.level == 1 || @user.level == 2 do %>
      <a class="btn btn-secondary" href="<%= cache_path(@conn, :down, @cache.id) %>" role="button">
        <i class="fa fa-fw fa-arrow-down" aria-hidden="true"></i> Send down
      </a>
    <% end %>

    <%= if @user.level == 1 do %>
      <button class="btn btn-success" type="button" data-toggle="modal" data-target="#cachePublishModal">
        <i class="fa fa-fw fa-check" aria-hidden="true"></i> Publish
      </button>
    <% else %>
      <a class="btn btn-secondary" href="<%= cache_path(@conn, :up, @cache.id) %>" role="button">
        <i class="fa fa-fw fa-arrow-up" aria-hidden="true"></i> Submit
      </a>
    <% end %>
    <button class="btn btn-danger" type="button" data-toggle="modal" data-target="#cacheDeleteModal">
      <i class="fa fa-fw fa-trash" aria-hidden="true"></i> Delete
    </button>
  </div>

  <%= if @cache.entries == [] do %>
    <div class="alert alert-info">
      This Working Cache contains no entries.
    </div>
  <% else %>
    <div class="list-group">
      <%= for entry <- @cache.entries do %>
        <a href="<%= entry_path(@conn, :show, entry.id) %>" class="list-group-item">
          <%= render Artus.SharedView, "entry.html", %{entry: entry} %>
        </a>
      <% end %>
    </div>
  <% end %>

</div>

web/templates/cache/submit.html.eex
<%= render Artus.SharedView, "navbar.html", %{user: @user} %>

<div class="container main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/caches">Working Caches</a></li>
    <li class="breadcrumb-item"><a href="<%= cache_path(@conn, :show, @cache.id) %>"><%= @cache.name %></a></li>
    <li class="breadcrumb-item active">Submit Cache</li>
  </ol>

  <%= if @supervisor do %>
    <p>You are about to submit this Working Cache to:</p>

    <div class="card">
      <div class="card-block">
        <h3 class="card-title"><%= @supervisor.name %></h3>
        <p class="card-text"><%= lookup_role(@supervisor.level) %></p>
      </div>
    </div>

    <%= form_tag(cache_path(@conn, :supervisor_submit, @cache.id)) %>
      <input type="hidden" value="<%= @supervisor.id %>" name="supervisor">
			<div class="form-group">
				<label for="comment">Comment</label>
				<textarea class="form-control" id="comment" name="comment" rows="3"></textarea>
			</div>
			<button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>

  <% else %>
    <div class="alert alert-danger" role="alert">
      There is no person of your branch registered who represents a higher level.
    </div>
  <% end %>





  


</div>

web/templates/cache/up.html.eex
<%= render Artus.SharedView, "navbar.html", %{user: @user} %>

<div class="container main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/caches">Working Caches</a></li>
    <li class="breadcrumb-item"><a href="<%= cache_path(@conn, :show, @cache.id) %>"><%= @cache.name %></a></li>
    <li class="breadcrumb-item active">Send Cache upward</li>
  </ol>

  <%= if @supervisors do %>
    <div class="alert alert-info">
      You're about to submit this Working Cache to your supervising bibliographer.
    </div>
    
    <%= form_tag(cache_path(@conn, :send, @cache.id, :up)) %>
      <div class="form-group">
        <label for="subordinate">Subordinate / Recipient</label>
        <select class="form-control" id="recipient" name="recipient">
          <%= for supervisor <- @supervisors do %>
            <option value="<%= supervisor.id %>"><%= supervisor.name %></option>
          <% end %>
        </select>
      </div>

			<div class="form-group">
				<label for="comment">Comment</label>
				<textarea class="form-control" id="comment" name="comment" rows="3"></textarea>
			</div>
			<button type="submit" class="btn btn-primary float-right">
        <i class="fa fa-fw fa-arrow-up" aria-hidden="true"></i> Submit
      </button>
    </form>
  <% else %>
    <div class="alert alert-danger" role="alert">
      There is no person of your branch registered who represents a higher level.
    </div>
  <% end %>
</div>